### ISSUE TITLE
Regarding the "data relates to computers" code.

### ISSUE THREAD

**Issue by kisaacs** [kawilliams/mental-models-codes#6]
I think the prevalence of Windows here isn't because people relate data with computers but because people are used to file/folder systems and computers. Here it's not data as a whole but this specific case. I suggest breaking out those into their code under the umbrella of where data abstractions/mental model ideas come from.

This code might not be enough on its own, though Session 030 finds that data is related to database tables... though I think I might rather group that with the very prevalent "data means tables" -- which is separate from the "reliance on tables" subcode which I think is also an abstraction thing.

**Comment by kawilliams** [comment]
I agree with the computer file system being inspiration for the design, rather than "all data is computers." Like you suggested, we'll move them to "where data abstractions/mental model ideas come from."

These are my understandings of our TODOs based on your comment (please review @kisaacs ):
- [x] Move "Participants used file system icons that they cited as being from an operating system." and the 4 supporting sessions to a new code of "Explicitly stated origins of data abstractions/mental models" (and possibly add the code "Physical objects can also be used to represent data" as a subcode to this area)
- [x] Rename "the idea that data relates to computers is prevalent" to "the idea that data relates to *tables* is prevalent" and add Session 030 with their database tables (although now Session 010 and their Python dict would need to be re-evaluated)

**Comment by kisaacs** [comment]
Yes, these sound good to me.

I have a few further interesting "what is data" things I picked out, but I can add/alter the code or put it under an umbrella code in a later commit since it hasn't congealed quite yet in my mind. (I'm so far grouping related stuff under "data and visualization expectations")

**Comment by kawilliams** [comment]
Closed via PR #8
